export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';
export const SET_CUSTOMERS = 'SET_CUSTOMERS';
export const ERROR_CUSTOMERS = 'ERROR_CUSTOMERS';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';
